import Image from "next/image";
import Head from "next/head";
import { signIn } from "next-auth/client";

function Login() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="google-site-verification"
          content="xSk6gFznm5ngk5F-e_Acg0IkPd4klqkm8E2MFaAKAbY"
        />
        <link
          rel="shortcut icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/2021_Facebook_icon.svg/2048px-2021_Facebook_icon.svg.png"
          type="image/x-icon"
        />
        <title>Facebook 2.0</title>
      </Head>
      <div className="grid place-items-center">
        <Image
          src="https://links.papareact.com/t4i"
          height={400}
          width={400}
          objectFit="contain"
        />
        <button
          onClick={signIn}
          className="p-5 text-center text-white bg-blue-500 rounded-full cursor-pointer"
        >
          Login with Facebook
        </button>
      </div>
    </>
  );
}

export default Login;
